CONFIG_FILE = "config.env"
LOGGING_FILE = "err.log"
MODEL_DIR = "models/"
LLM_NAME = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

DB_NAME = "chatbot"

VECTORSTORE_COLLECTION_NAME = "vector_store"
VECTORSTORE_INDEX_NAME = "vector_index"
VECTORSTORE_EMBEDDING_KEY = "embedding"
VECTORSTORE_SEARCH_FUNC = "cosine"

CHAT_HISTORY_COLLECTION_NAME = "chat_history"
CHAT_HISTORY_SESSION_KEY = "sid"
CHAT_HISTORY_HISTORY_KEY = "history"

SPLITTER_CHUNK_SIZE = 1000
SPLITTER_CHUNK_OVERLAP = 25
MAX_READ_LINES_FOR_TEXT_FILE = 40

TEMP_DIR = "temp"
